In [1]:
import numpy as np

np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [5]:
np.linspace(2, 4, 5)

array([2. , 2.5, 3. , 3.5, 4. ])

In [6]:
np.random.randn(2, 3)

array([[ 1.2864043 , -0.24656661,  0.46346839],
       [ 0.19150343, -1.63669499,  0.02939655]])

In [14]:
np.random.randint(1, 11, 5)

array([10,  1,  4,  4,  8])

In [5]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
b = a.reshape(5, 5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
b.shape

(5, 5)

In [9]:
b.dtype

dtype('int32')