# NumPy Indexing

How does it differ from regular python indexing?

In [2]:
import numpy as np

In [10]:
a = np.arange(10)

In [11]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a[4]

4

In [14]:
a[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a[3:6]

array([3, 4, 5])

In [18]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a[1:6] = 10000

In [28]:
a

array([    0, 10000, 10000, 10000, 10000, 10000,     6,     7,     8,
           9])

In [7]:
hahaha = [0, 1, 2, 3, 4, 5]

hahaha[2:3] = 1

hahaha

# vai dar erro

TypeError: can only assign an iterable

In [6]:
a = np.arange(0, 6) #certo
a[2:4] = 6
a

array([0, 1, 6, 6, 4, 5])

# Index Broadcasting

In [35]:
a = np.arange(10)

In [30]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b = a[:]

In [32]:
b[:] = 0

In [33]:
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
b = a.copy()

In [37]:
b[:] = 10000

In [38]:
b

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000])

In [39]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexing A 2D Array / Matrix

In [48]:
c = np.array([[1,2,3],[2,3,4], [3,4,5]])

In [49]:
c

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [50]:
c[0,1]

2

In [51]:
c[0][1]

2

In [52]:
c[2,2]

5

In [53]:
c[:2,1:]

array([[2, 3],
       [3, 4]])

In [54]:
c[:2]

array([[1, 2, 3],
       [2, 3, 4]])

# Conditional Indexing

In [69]:
a = np.arange(10)

In [70]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [72]:
b = a>5

In [73]:
b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [74]:
a[b]

array([6, 7, 8, 9])

In [75]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a[a>5]

array([6, 7, 8, 9])

# NumPy Operations

1. Array with arrays
2. Array with scalars

In [85]:
a = np.arange(10)

In [86]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a + a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [88]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [89]:
a * a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [90]:
a + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
a - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [92]:
a * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [93]:
1/0

ZeroDivisionError: division by zero

In [94]:
a / a

<ipython-input-94-bb29898574ab>:1: RuntimeWarning: invalid value encountered in true_divide
  a / a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [95]:
1 / a

<ipython-input-95-0c5dc1e9adcb>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / a


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

# Numpy Operations

Universal Functions

In [96]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [97]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [98]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [99]:
np.log(a)

<ipython-input-99-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])